//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortnerForm.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUrlShortner")]
    public interface IUrlShortner {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrlShortner/GetShortUrl", ReplyAction="http://tempuri.org/IUrlShortner/GetShortUrlResponse")]
        string GetShortUrl(string orignalUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrlShortner/GetShortUrl", ReplyAction="http://tempuri.org/IUrlShortner/GetShortUrlResponse")]
        System.Threading.Tasks.Task<string> GetShortUrlAsync(string orignalUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrlShortner/GetOriginalUrl", ReplyAction="http://tempuri.org/IUrlShortner/GetOriginalUrlResponse")]
        string GetOriginalUrl(string shortUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrlShortner/GetOriginalUrl", ReplyAction="http://tempuri.org/IUrlShortner/GetOriginalUrlResponse")]
        System.Threading.Tasks.Task<string> GetOriginalUrlAsync(string shortUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUrlShortnerChannel : URLShortnerForm.ServiceReference1.IUrlShortner, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UrlShortnerClient : System.ServiceModel.ClientBase<URLShortnerForm.ServiceReference1.IUrlShortner>, URLShortnerForm.ServiceReference1.IUrlShortner {
        
        public UrlShortnerClient() {
        }
        
        public UrlShortnerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UrlShortnerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrlShortnerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UrlShortnerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetShortUrl(string orignalUrl) {
            return base.Channel.GetShortUrl(orignalUrl);
        }
        
        public System.Threading.Tasks.Task<string> GetShortUrlAsync(string orignalUrl) {
            return base.Channel.GetShortUrlAsync(orignalUrl);
        }
        
        public string GetOriginalUrl(string shortUrl) {
            return base.Channel.GetOriginalUrl(shortUrl);
        }
        
        public System.Threading.Tasks.Task<string> GetOriginalUrlAsync(string shortUrl) {
            return base.Channel.GetOriginalUrlAsync(shortUrl);
        }
    }
}
